version: '2'

networks:
  frontend:
  backend:

volumes:
  mysql_db:
    driver: local
  mysql_log:
    driver: local
  nginx_log:
    driver: local

services:

  mirth-connect:
    build: mirth-connect
    image: fabrom/mirth-connect
    container_name: mc-mirthconnect
    restart: on-failure
    volumes:
      - "./mirth-connect/conf/mirth.properties:/opt/mirth-connect/conf/mirth.properties:rw"
      - "./data/mirth-connect/conf/dbdrivers.xml:/opt/mirth-connect/conf/dbdrivers.xml:rw"
      - "./data/mirth-connect/custom-lib/:/opt/mirth-connect/custom-lib/:ro"
      - "./data/mirth-connect/spools/:/var/spool/mirth/:rw"
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - mirth-database:mysql
      - rp-https:rp-https
    networks:
      - frontend
      - backend
    depends_on:
      - mirth-database
      - rp-https

  phpmyadmin:
    container_name: mc-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    ports:
      - "8181:80"
    environment:
      - "MYSQL_USERNAME=root"
      - "MYSQL_PASSWORD=password"
    links:
      - mirth-database:db
    networks:
      - frontend
      - backend
    depends_on:
      - mirth-database

  mirth-database:
    container_name: mc-mysql
    image: mysql:5.6
    command: mysqld --innodb-buffer-pool-size=20M
    restart: on-failure
    volumes:
      - "mysql_db:/var/lib/mysql:rw"
      - "mysql_log:/var/log/mysql:rw"
    environment:
      - "MYSQL_DATABASE=mirth-test"
      - "MYSQL_USER=mirth"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    networks:
      - backend

  rp-https:
    container_name: mc-rp-https
    hostname: rp-https
    image: nginx:latest
    restart: on-failure
    ports:
      - 7980:7980  # for from host reverse testing
    volumes:
      - "./data/rp-https/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./data/rp-https/conf/nginx/conf.d/:/etc/nginx/conf.d/:ro"
      - "./data/rp-https/conf/ssl/:/etc/ssl/private/:ro"
      - "nginx_log:/var/log/nginx"
    networks:
      - backend
